name: Update Guestbook

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:      # Allows manual triggering

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  update_guestbook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Update Guestbook Feed
        uses: nfhipona/guestbook-workflow@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'main'
          section_identifier: 'guestbook-section'
          entry_labels: ''
          comment_link_template: ' '

